Add new Ansible role to replace addon manager
The new Ansible role is called `keights-system` and is used to
set up the `kube-system` namespace in the way that the addon
manager did. Using the addon manager required changes to the AMI
if it needed modifying, and slowed down development time and the
ability to modify the cluster.

diff --git a/build/github-release b/build/github-release
--- a/build/github-release
+++ b/build/github-release
@@ -70,8 +70,11 @@ for bot in ${bots}; do
     upload "${bot_artifact}" "${bot_artifact_path}" "${release_id}" || fail "`cat ${out_file}`"
 done
 
-# Ansible role
-role_artifact="keights-stack-${VERSION}.tar.gz"
-role_artifact_path="_output/${role_artifact}"
-[ -f ${role_artifact_path} ] || fail "${role_artifact_path} not found"
-upload "${role_artifact}" "${role_artifact_path}" "${release_id}" || fail "`cat ${out_file}`"
+# Ansible roles
+roles="keights-stack keights-system"
+for role in ${roles}; do
+    role_artifact="${role}-${VERSION}.tar.gz"
+    role_artifact_path="_output/${role_artifact}"
+    [ -f ${role_artifact_path} ] || fail "${role_artifact_path} not found"
+    upload "${role_artifact}" "${role_artifact_path}" "${release_id}" || fail "`cat ${out_file}`"
+done
